"""
Real Indian government welfare scheme definitions with eligibility criteria.

This module has NO dependency on the database or SQLAlchemy — it's pure
data — so it can be imported by the rule engine, the training script, and
tests without needing a live DB connection.

Eligibility figures here are approximate, based on publicly documented
scheme criteria as of general knowledge — VERIFY against the official
scheme websites before quoting exact numbers in your demo/pitch, since
income thresholds and rules are periodically revised by the government.
"""

SCHEMES = [
    dict(
        name="PM-KISAN",
        short_description="Income support of ₹6,000/year for landholding farmer families.",
        min_income=0, max_income=None,
        occupation_list=["farmer"],
        age_min=18, age_max=100,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=True,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Land ownership records", "Bank account details"],
        apply_url="https://pmkisan.gov.in/",
    ),
    dict(
        name="Ayushman Bharat (PM-JAY)",
        short_description="Health cover of ₹5 lakh/family/year for secondary & tertiary care.",
        min_income=0, max_income=250000,
        occupation_list=None,
        age_min=0, age_max=100,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Ration card / SECC data proof", "Income certificate"],
        apply_url="https://pmjay.gov.in/",
    ),
    dict(
        name="PM Awas Yojana (Urban)",
        short_description="Affordable housing assistance for EWS/LIG/MIG households.",
        min_income=0, max_income=1800000,
        occupation_list=None,
        age_min=18, age_max=100,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Income certificate", "No-existing-house declaration"],
        apply_url="https://pmaymis.gov.in/",
    ),
    dict(
        name="National Scholarship Portal — Pre-Matric",
        short_description="Scholarship support for economically weaker students in schools.",
        min_income=0, max_income=250000,
        occupation_list=None,
        age_min=5, age_max=18,
        gender="any",
        category_eligible=["SC", "ST", "OBC"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=True,
        document_checklist=["Aadhaar card", "Income certificate", "School bonafide certificate"],
        apply_url="https://scholarships.gov.in/",
    ),
    dict(
        name="PM Ujjwala Yojana",
        short_description="Free LPG connections for women from BPL households.",
        min_income=0, max_income=100000,
        occupation_list=None,
        age_min=18, age_max=100,
        gender="female",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "BPL ration card", "Bank account details"],
        apply_url="https://pmuy.gov.in/",
    ),
    dict(
        name="Sukanya Samriddhi Yojana",
        short_description="Savings scheme for the future education/marriage of a girl child.",
        min_income=0, max_income=None,
        occupation_list=None,
        age_min=0, age_max=10,
        gender="female",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Girl child's birth certificate", "Guardian's Aadhaar & PAN"],
        apply_url="https://www.india.gov.in/sukanya-samriddhi-yojana",
    ),
    dict(
        name="Atal Pension Yojana",
        short_description="Guaranteed pension scheme for unorganized-sector workers.",
        min_income=0, max_income=None,
        occupation_list=["laborer", "self_employed", "unorganized_worker", "street_vendor"],
        age_min=18, age_max=40,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Bank account", "Mobile number"],
        apply_url="https://npscra.nsdl.co.in/scheme-details.php",
    ),
    dict(
        name="PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
        short_description="Collateral-free working capital loans for street vendors.",
        min_income=0, max_income=None,
        occupation_list=["street_vendor"],
        age_min=18, age_max=100,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Vendor certificate/ID", "Bank account details"],
        apply_url="https://pmsvanidhi.mohua.gov.in/",
    ),
    dict(
        name="e-Shram Registration Benefits",
        short_description="Social security registration & benefits for unorganized workers.",
        min_income=0, max_income=None,
        occupation_list=["laborer", "unorganized_worker", "domestic_worker", "self_employed"],
        age_min=16, age_max=59,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Bank account details", "Mobile number"],
        apply_url="https://eshram.gov.in/",
    ),
    dict(
        name="Indira Gandhi National Old Age Pension Scheme",
        short_description="Monthly pension for BPL citizens above 60 years.",
        min_income=0, max_income=100000,
        occupation_list=None,
        age_min=60, age_max=100,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Age proof", "BPL certificate"],
        apply_url="https://nsap.nic.in/",
    ),
    dict(
        name="Indira Gandhi National Widow Pension Scheme",
        short_description="Monthly pension support for BPL widows.",
        min_income=0, max_income=100000,
        occupation_list=None,
        age_min=40, age_max=79,
        gender="female",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Husband's death certificate", "BPL certificate"],
        apply_url="https://nsap.nic.in/",
    ),
    dict(
        name="Indira Gandhi National Disability Pension Scheme",
        short_description="Monthly pension for BPL persons with severe disability.",
        min_income=0, max_income=100000,
        occupation_list=None,
        age_min=18, age_max=79,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Disability certificate (80%+)", "BPL certificate"],
        apply_url="https://nsap.nic.in/",
    ),
    dict(
        name="National Scholarship Portal — Post-Matric",
        short_description="Scholarship support for SC/ST/OBC students in college.",
        min_income=0, max_income=250000,
        occupation_list=None,
        age_min=17, age_max=35,
        gender="any",
        category_eligible=["SC", "ST", "OBC"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=True,
        document_checklist=["Aadhaar card", "Income certificate", "College bonafide certificate"],
        apply_url="https://scholarships.gov.in/",
    ),
    dict(
        name="PM Fasal Bima Yojana",
        short_description="Crop insurance against yield loss due to natural calamities.",
        min_income=0, max_income=None,
        occupation_list=["farmer"],
        age_min=18, age_max=100,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=True,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Land records", "Bank account details"],
        apply_url="https://pmfby.gov.in/",
    ),
    dict(
        name="Beti Bachao Beti Padhao — allied benefits",
        short_description="Awareness & incentive scheme improving welfare of the girl child.",
        min_income=0, max_income=None,
        occupation_list=None,
        age_min=0, age_max=18,
        gender="female",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Girl child's birth certificate", "Guardian's Aadhaar"],
        apply_url="https://wcd.nic.in/bbbp-schemes",
    ),
    dict(
        name="Pradhan Mantri Jan Dhan Yojana",
        short_description="Zero-balance bank account access for financial inclusion.",
        min_income=0, max_income=None,
        occupation_list=None,
        age_min=10, age_max=100,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card / any valid ID"],
        apply_url="https://pmjdy.gov.in/",
    ),
    dict(
        name="Stand-Up India Scheme",
        short_description="Bank loans for SC/ST and women entrepreneurs to set up new enterprises.",
        min_income=0, max_income=None,
        occupation_list=["self_employed"],
        age_min=18, age_max=100,
        gender="any",
        category_eligible=["SC", "ST"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Business plan", "Caste certificate"],
        apply_url="https://www.standupmitra.in/",
    ),
    dict(
        name="PM Mudra Yojana",
        short_description="Collateral-free loans up to ₹10 lakh for small/micro enterprises.",
        min_income=0, max_income=None,
        occupation_list=["self_employed", "small_business_owner"],
        age_min=18, age_max=100,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Aadhaar card", "Business proof", "Bank account details"],
        apply_url="https://www.mudra.org.in/",
    ),
    dict(
        name="National Family Benefit Scheme",
        short_description="One-time financial assistance to BPL families on death of the breadwinner.",
        min_income=0, max_income=100000,
        occupation_list=None,
        age_min=18, age_max=59,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=False,
        document_checklist=["Death certificate", "BPL certificate", "Aadhaar card"],
        apply_url="https://nsap.nic.in/",
    ),
    dict(
        name="PM POSHAN (Mid-Day Meal Scheme)",
        short_description="Free school meals for government/aided school students.",
        min_income=0, max_income=None,
        occupation_list=None,
        age_min=5, age_max=14,
        gender="any",
        category_eligible=["SC", "ST", "OBC", "General"],
        state_scope="central",
        land_ownership_required=False,
        student_status_required=True,
        document_checklist=["School enrollment proof"],
        apply_url="https://pmposhan.education.gov.in/",
    ),
]
